spring:
  application:
    name: alpha-vault-backend\
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alpha_vault
    username: root
    password: 123456

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.jaychou.alphavault.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
